/**
 * Prompt templates mac dinh — nguon su that duy nhat cho:
 * (1) seed migration vao bang prompt_templates, (2) fallback khi DB chua co row
 * (vd: chay unit test voi in-memory repo, hoac migration chua chay).
 *
 * Noi dung prompt la user-facing text -> BAT BUOC tieng Viet co dau day du.
 * Doi prompt o production: tao version moi trong DB, KHONG sua file nay
 * (file nay chi la baseline v-dau-tien).
 */

export const SYSTEM_PROMPT_KEY = "article.system.vi";

export const PROMPT_KEYS = {
  system: SYSTEM_PROMPT_KEY,
  outline: (articleType: string) => `${articleType}.outline.vi`,
  section: (articleType: string) => `${articleType}.section.vi`,
  frame: (articleType: string) => `${articleType}.frame.vi`,
} as const;

/** Quy tac ngon ngu nhung vao moi prompt — rule bat buoc cua du an. */
const VIETNAMESE_RULE = [
  `- BẮT BUỘC viết tiếng Việt có dấu đầy đủ trong toàn bộ nội dung.`,
  `- Nếu chủ đề hoặc dữ liệu đầu vào không dấu, hãy chuẩn hóa lại thành tiếng Việt có dấu.`,
].join("\n");

const NO_FABRICATION_RULE = [
  `- CHỈ dùng thông tin sản phẩm có trong dữ liệu được cung cấp, KHÔNG tự chế thông số, giá, khuyến mãi.`,
  `- KHÔNG claim quá đà ("tốt nhất thị trường", "cam kết 100%", claim y khoa...).`,
].join("\n");

export const DEFAULT_PROMPTS: Readonly<Record<string, string>> = {
  [SYSTEM_PROMPT_KEY]: [
    `Bạn là chuyên gia viết content affiliate tiếng Việt cho website thương mại.`,
    `Bạn LUÔN viết tiếng Việt có dấu đầy đủ, viết trung thực, chỉ dùng dữ liệu được cung cấp,`,
    `tuân thủ schema output nghiêm ngặt.`,
  ].join(" "),

  // ===== TOP-LIST (spec §17.2-B) =====
  "toplist.outline.vi": [
    `Tạo OUTLINE cho bài viết TOP-LIST (danh sách sản phẩm tốt nhất) tiếng Việt.`,
    `Chủ đề: {{topic}}`,
    `Từ khóa chính: {{keywords}}`,
    `Website: {{siteCode}}`,
    `Giọng văn: {{toneProfile}}`,
    `Dữ liệu sản phẩm (JSON): {{products}}`,
    ``,
    `Yêu cầu:`,
    VIETNAMESE_RULE,
    `- title: 50-70 ký tự, chứa từ khóa chính một cách tự nhiên.`,
    `- sectionHeadings: 3-5 mục H2, BẮT BUỘC có "Tiêu chí xếp hạng" và "Cách chọn mua theo ngân sách".`,
    `- plannedProducts: chọn các sản phẩm phù hợp nhất từ dữ liệu; nếu danh sách rỗng thì để mảng rỗng.`,
    `- plannedFaqQuestions: 3-6 câu hỏi theo search intent thực tế của người mua.`,
    NO_FABRICATION_RULE,
  ].join("\n"),

  "toplist.section.vi": [
    `Viết nội dung cho MỘT section của bài top-list tiếng Việt.`,
    `Bài viết: {{title}}`,
    `Section cần viết (heading phải giữ nguyên): {{sectionHeading}}`,
    `Toàn bộ outline (để giữ mạch bài, KHÔNG lặp nội dung section khác): {{outline}}`,
    `Dữ liệu sản phẩm (JSON): {{products}}`,
    `Giọng văn: {{toneProfile}}`,
    ``,
    `Yêu cầu:`,
    VIETNAMESE_RULE,
    `- content: 120-250 từ, giọng tự nhiên như người viết thật, không khoa trương.`,
    `- Đi thẳng vào nội dung của section này, không viết lại mở bài.`,
    NO_FABRICATION_RULE,
  ].join("\n"),

  "toplist.frame.vi": [
    `Hoàn thiện KHUNG bài viết top-list tiếng Việt (mọi block TRỪ các section chính đã viết xong).`,
    `Chủ đề: {{topic}}`,
    `Từ khóa chính: {{keywords}}`,
    `Website: {{siteCode}}`,
    `Outline: {{outline}}`,
    `Tóm tắt các section đã viết: {{sectionsSummary}}`,
    `Dữ liệu sản phẩm (JSON): {{products}}`,
    `Giọng văn: {{toneProfile}}`,
    ``,
    `Yêu cầu:`,
    VIETNAMESE_RULE,
    `- hero.title: giữ đúng title trong outline. hero.affiliateDisclosure: câu khai báo tiếp thị liên kết rõ ràng.`,
    `- intent: bài dành cho ai, giải quyết vấn đề gì. quickAnswer: 3-5 bullet kết luận nhanh.`,
    `- productRecommendations: theo mẫu top-list — vì sao trong danh sách, ưu/nhược, mức giá tham khảo,`,
    `  đối tượng phù hợp. CHỈ dùng sản phẩm trong dữ liệu; nếu dữ liệu rỗng, dùng productUrl`,
    `  "https://example.com/placeholder" và ghi rõ trong whyInList rằng cần bổ sung dữ liệu thật.`,
    `- faq: trả lời các câu hỏi trong outline, mỗi câu 2-4 câu văn.`,
    `- finalCta: gợi ý item ưu tiên, không claim quá đà.`,
    `- metadata.metaTitle <= 70 ký tự, metaDescription <= 170 ký tự,`,
    `  internalLinkSuggestions: 2 đường dẫn nội bộ dạng "/ten-bai-viet" (slug không dấu).`,
    NO_FABRICATION_RULE,
  ].join("\n"),

  // ===== REVIEW DON (spec §17.2-A) =====
  "review.outline.vi": [
    `Tạo OUTLINE cho bài REVIEW MỘT SẢN PHẨM tiếng Việt.`,
    `Chủ đề: {{topic}}`,
    `Từ khóa chính: {{keywords}}`,
    `Website: {{siteCode}}`,
    `Giọng văn: {{toneProfile}}`,
    `Dữ liệu sản phẩm (JSON): {{products}}`,
    ``,
    `Yêu cầu:`,
    VIETNAMESE_RULE,
    `- title: 50-70 ký tự, chứa tên sản phẩm + từ khóa chính tự nhiên.`,
    `- sectionHeadings: 4-5 mục H2 theo khung review: giới thiệu nhanh sản phẩm và đối tượng dùng;`,
    `  ưu điểm và hạn chế; trải nghiệm theo tiêu chí (chất liệu/độ bền, tính năng, giá trị trên giá tiền);`,
    `  so sánh nhẹ với 1-2 lựa chọn cùng phân khúc; kết luận có nên mua không.`,
    `- plannedProducts: sản phẩm chính được review + 1-2 sản phẩm so sánh (nếu có trong dữ liệu).`,
    `- plannedFaqQuestions: 3-6 câu hỏi người mua hay hỏi trước khi xuống tiền.`,
    NO_FABRICATION_RULE,
  ].join("\n"),

  "review.section.vi": [
    `Viết nội dung cho MỘT section của bài review sản phẩm tiếng Việt.`,
    `Bài viết: {{title}}`,
    `Section cần viết (heading phải giữ nguyên): {{sectionHeading}}`,
    `Toàn bộ outline (để giữ mạch bài, KHÔNG lặp nội dung section khác): {{outline}}`,
    `Dữ liệu sản phẩm (JSON): {{products}}`,
    `Giọng văn: {{toneProfile}}`,
    ``,
    `Yêu cầu:`,
    VIETNAMESE_RULE,
    `- content: 120-250 từ, trung thực, nêu cả điểm chưa tốt nếu dữ liệu cho thấy.`,
    `- Đi thẳng vào nội dung của section này, không viết lại mở bài.`,
    NO_FABRICATION_RULE,
  ].join("\n"),

  "review.frame.vi": [
    `Hoàn thiện KHUNG bài review sản phẩm tiếng Việt (mọi block TRỪ các section chính đã viết xong).`,
    `Chủ đề: {{topic}}`,
    `Từ khóa chính: {{keywords}}`,
    `Website: {{siteCode}}`,
    `Outline: {{outline}}`,
    `Tóm tắt các section đã viết: {{sectionsSummary}}`,
    `Dữ liệu sản phẩm (JSON): {{products}}`,
    `Giọng văn: {{toneProfile}}`,
    ``,
    `Yêu cầu:`,
    VIETNAMESE_RULE,
    `- hero.title: giữ đúng title trong outline. hero.affiliateDisclosure: câu khai báo tiếp thị liên kết rõ ràng.`,
    `- intent: ai nên đọc review này. quickAnswer: 3-5 bullet kết luận nhanh (có nên mua, ai nên mua).`,
    `- productRecommendations: sản phẩm chính + tối đa 2 lựa chọn thay thế cùng phân khúc,`,
    `  mỗi item ghi rõ ưu/nhược và đối tượng phù hợp. CHỈ dùng sản phẩm trong dữ liệu;`,
    `  nếu dữ liệu rỗng, dùng productUrl "https://example.com/placeholder" và ghi rõ cần bổ sung dữ liệu thật.`,
    `- faq: trả lời các câu hỏi trong outline, mỗi câu 2-4 câu văn.`,
    `- finalCta: kết luận có nên mua không, không claim quá đà.`,
    `- metadata.metaTitle <= 70 ký tự, metaDescription <= 170 ký tự,`,
    `  internalLinkSuggestions: 2 đường dẫn nội bộ dạng "/ten-bai-viet" (slug không dấu).`,
    NO_FABRICATION_RULE,
  ].join("\n"),

  // ===== GUIDE ĐIỂM ĐẾN dichoithoi.com (dichoithoi-destination-spec §2.2, §4) =====
  "guide-diem-den.outline.vi": [
    `Tạo OUTLINE cho bài viết GIỚI THIỆU ĐIỂM ĐẾN DU LỊCH Việt Nam, chuẩn SEO,`,
    `giọng văn như người đã đi thực tế viết lại — không liệt kê khô khan.`,
    `Điểm đến: {{topic}}`,
    `Từ khóa chính: {{keywords}}`,
    `Giọng văn: {{toneProfile}}`,
    `DỮ LIỆU ĐIỂM ĐẾN (nguồn sự thật — ưu tiên tuyệt đối khi viết):`,
    `{{sourceContext}}`,
    ``,
    `Yêu cầu:`,
    VIETNAMESE_RULE,
    `- title: 50-70 ký tự, chứa tên điểm đến, gợi đúng search intent du lịch`,
    `  (ví dụ "Vịnh Hạ Long: kinh nghiệm tham quan, giá vé, ăn gì 2026").`,
    `- sectionHeadings: ĐÚNG 7 mục H2 theo THỨ TỰ CỐ ĐỊNH sau (không thêm/bớt/đổi thứ tự,`,
    `  có thể chỉnh câu chữ cho tự nhiên nhưng phải giữ đúng ý nghĩa từng mục — KHÔNG có mục`,
    `  "mẹo & lưu ý": phần đó đã có cơ chế riêng, tránh trùng nội dung với các mục dưới đây):`,
    `  1. "Tổng quan/giới thiệu về {{topic}}" (vì sao đáng đi, nét đặc trưng).`,
    `  2. "Trải nghiệm gì ở {{topic}}" (khách sẽ LÀM GÌ cụ thể ở đây — sẽ viết dạng DANH SÁCH,`,
    `     KHÁC "điểm tham quan": đây là hành động/hoạt động, không phải tên địa điểm).`,
    `  3. "Nên đi {{topic}} vào mùa nào" (BẮT BUỘC chứa từ "mùa" hoặc "thời điểm").`,
    `  4. "Lịch trình gợi ý khi đi {{topic}}" ({{topic}} là 1 điểm tham quan LẺ — viết nên dành`,
    `     bao lâu ở đây (ví dụ "khoảng 45-90 phút") và có thể kết hợp đi cùng điểm nào gần đó`,
    `     TRONG cùng buổi/ngày, KHÔNG viết lịch trình nhiều ngày cho cả vùng — đó là bài giới`,
    `     thiệu tổng quan của điểm đến lớn hơn, không phải bài này).`,
    `  5. "Di chuyển tới {{topic}}" (cách tới nơi, phương tiện).`,
    `  6. "Ăn gì đặc trưng ở {{topic}}" (món/đặc sản tiêu biểu — sẽ viết dạng DANH SÁCH).`,
    `  7. "Quà mang về từ {{topic}}" (đặc sản mua làm quà — sẽ viết dạng DANH SÁCH).`,
    `- plannedFaqQuestions: 3-6 câu đúng search intent thực tế (có nên đi, đi mùa nào, mất bao lâu, lưu ý gì...).`,
    `- KHÔNG tự chế số liệu (giá vé, giờ, khoảng cách) ngoài dữ liệu được cung cấp.`,
  ].join("\n"),

  "guide-diem-den.section.vi": [
    `Viết nội dung cho MỘT section của bài giới thiệu điểm đến du lịch tiếng Việt.`,
    `Bài viết: {{title}}`,
    `Section cần viết (heading phải giữ nguyên): {{sectionHeading}}`,
    `Toàn bộ outline (giữ mạch bài, KHÔNG lặp nội dung section khác): {{outline}}`,
    `DỮ LIỆU ĐIỂM ĐẾN (nguồn sự thật): {{sourceContext}}`,
    `Giọng văn: {{toneProfile}}`,
    ``,
    `Yêu cầu:`,
    VIETNAMESE_RULE,
    `- blockKey: BẮT BUỘC gán đúng 1 trong 7 giá trị sau theo đúng ý nghĩa heading đang viết —`,
    `  "tong-quan" | "trai-nghiem" | "mua-nao" | "lich-trinh" | "di-chuyen" | "an-gi" |`,
    `  "qua-mang-ve".`,
    `- content: 120-250 từ, như người đi thực tế kể lại — có chi tiết cụ thể, cảm nhận thật,`,
    `  tránh văn mẫu sáo rỗng kiểu "điểm đến hấp dẫn không thể bỏ qua".`,
    `- Nếu blockKey là "lich-trinh": viết dạng văn xuôi bình thường (KHÔNG dùng "items"), gợi ý`,
    `  thời lượng nên dành + có thể kết hợp điểm nào gần đó, KHÔNG lặp lại nội dung đã nói ở`,
    `  khối "trai-nghiem" (khối đó là DANH SÁCH hoạt động, khối này là GỢI Ý SẮP XẾP thời gian).`,
    `- NẾU blockKey là "trai-nghiem" | "an-gi" | "qua-mang-ve": BẮT BUỘC điền thêm "items" — mảng`,
    `  ít nhất 3 mục {ten, moTa}. Với "trai-nghiem": "ten" là 1 HÀNH ĐỘNG/HOẠT ĐỘNG cụ thể khách`,
    `  làm được ở đây (KHÔNG phải tên địa điểm — đó là việc của khối "điểm tham quan" riêng),`,
    `  "moTa" nêu cách làm/vị trí cụ thể (vd leo cầu thang nào, chụp ảnh góc nào, mất bao lâu).`,
    `  Với "an-gi"/"qua-mang-ve": "ten" là 1 món ăn/đặc sản cụ thể, "moTa" là mô tả ngắn 1-2 câu`,
    `  (vị trí mua/đặc điểm nổi bật). "content" khi đó chỉ cần 1 câu dẫn ngắn, KHÔNG lặp lại`,
    `  nội dung đã có trong "items", và KHÔNG lặp lại ý đã nói ở khối "tong-quan".`,
    `- Nếu bài nhắc tới điểm đến khác trong danh sách điểm liên quan (trong dữ liệu),`,
    `  dùng đúng TÊN CHUẨN của điểm đó để hệ thống tự gắn link.`,
    `- Số liệu (giá, giờ, khoảng cách) CHỈ lấy từ dữ liệu cung cấp; thiếu thì viết định tính,`,
    `  không bịa con số.`,
  ].join("\n"),

  "guide-diem-den.frame.vi": [
    `Hoàn thiện KHUNG bài giới thiệu điểm đến (mọi phần TRỪ các section chính đã viết xong).`,
    `Điểm đến: {{topic}}`,
    `Từ khóa chính: {{keywords}}`,
    `Outline: {{outline}}`,
    `Tóm tắt các section đã viết: {{sectionsSummary}}`,
    `DỮ LIỆU ĐIỂM ĐẾN (nguồn sự thật): {{sourceContext}}`,
    `Giọng văn: {{toneProfile}}`,
    ``,
    `Yêu cầu:`,
    VIETNAMESE_RULE,
    `- title: giữ đúng title trong outline.`,
    `- intro: 80-150 từ mở bài tự nhiên, chứa tên điểm đến, nêu cả địa chỉ MỚI và địa chỉ CŨ`,
    `  (trước sáp nhập) nếu dữ liệu có đủ cả hai.`,
    `- quickFacts (dữ liệu hiển thị dạng thẻ — NGẮN GỌN, đúng sự thật):`,
    `  openingTime, ticketPrice: lấy từ dữ liệu; thiếu thì ghi "Cần kiểm tra lại" — KHÔNG bịa.`,
    `  Giá vé luôn kèm "có thể thay đổi". Điểm miễn phí ghi "Miễn phí".`,
    `  transport: cách di chuyển tới nơi (từ trung tâm, phương tiện). food: ăn gì tại chỗ/gần đó.`,
    `  hotel: nên ở khu nào. tip: 2-4 mẹo thực tế.`,
    `- faq: trả lời các câu hỏi trong outline, mỗi câu 2-4 câu văn.`,
    `- updateNotice: ghi ĐÚNG NGUYÊN VĂN "Thông tin trong bài cập nhật tháng {{currentDate}},`,
    `  giá vé và giờ mở cửa có thể thay đổi." — dùng đúng tháng/năm {{currentDate}} được cung cấp,`,
    `  KHÔNG tự suy ra từ kiến thức nền.`,
    `- metadata: name = tên chuẩn có dấu; slugSuggestion = slug không dấu;`,
    `  metaTitle <= 140 ký tự; metaDescription 100-290 ký tự chứa từ khóa;`,
    `  description = mô tả 1-2 câu (50-900 ký tự); searchKeyword = các từ người dùng hay gõ, cách nhau dấu phẩy.`,
    `- KHÔNG claim tuyệt đối ("đẹp nhất Việt Nam", "duy nhất", "rẻ nhất") khi không có nguồn.`,
  ].join("\n"),

  // ===== GUIDE ĐIỂM ĐẾN FLAGSHIP dichoithoi.com — tỉnh/cụm tổng hợp có ContentTier=flagship
  // (content-seo-ux-plan §10.6.2, Phase 28.3). Cùng schema guide-diem-den (destinationArticleSchema)
  // nhưng khác trọng tâm: node này KHÔNG có 1 giờ mở cửa/giá vé duy nhất (gồm nhiều điểm con),
  // nên bỏ khung "điểm đến đơn lẻ" và thay bằng góc nhìn "cả điểm đến/vùng": mùa nào đẹp, di
  // chuyển 2 chiều tới đó, ăn gì đặc trưng vùng, mang gì về — quickFacts vẫn theo đúng schema cũ
  // (openingTime/ticketPrice) nhưng nội dung ghi "Tuỳ điểm tham quan cụ thể" thay vì bịa 1 con số.
  "guide-diem-den-flagship.outline.vi": [
    `Tạo OUTLINE cho bài viết GIỚI THIỆU TỔNG QUAN 1 ĐIỂM ĐẾN LỚN (tỉnh/thành hoặc`,
    `cụm du lịch nổi tiếng, gồm NHIỀU điểm tham quan con — khác bài giới thiệu 1`,
    `điểm tham quan đơn lẻ), chuẩn SEO, giọng văn người am hiểu vùng đất viết lại.`,
    `Điểm đến: {{topic}}`,
    `Từ khóa chính: {{keywords}}`,
    `Giọng văn: {{toneProfile}}`,
    `DỮ LIỆU ĐIỂM ĐẾN (nguồn sự thật — ưu tiên tuyệt đối khi viết):`,
    `{{sourceContext}}`,
    ``,
    `Yêu cầu:`,
    VIETNAMESE_RULE,
    `- title: 50-70 ký tự, chứa tên điểm đến, gợi search intent tổng quan`,
    `  (ví dụ "Đà Lạt: kinh nghiệm du lịch, đi mùa nào, chơi gì, ăn gì 2026").`,
    `- sectionHeadings: ĐÚNG 7 mục H2 theo THỨ TỰ CỐ ĐỊNH sau (không thêm/bớt/đổi thứ tự,`,
    `  có thể chỉnh câu chữ tự nhiên nhưng giữ đúng ý nghĩa, ở tầm TỔNG QUAN cả vùng —`,
    `  không đi sâu 1 điểm tham quan con cụ thể; KHÔNG có mục "mẹo & lưu ý": phần đó đã có`,
    `  cơ chế riêng, tránh trùng nội dung với các mục dưới đây):`,
    `  1. "Tổng quan/giới thiệu về {{topic}}" (nét đặc trưng cả vùng).`,
    `  2. "Trải nghiệm gì ở {{topic}}" (hoạt động tiêu biểu CẢ VÙNG — sẽ viết dạng DANH SÁCH,`,
    `     KHÁC "điểm tham quan": đây là hành động, không phải tên địa điểm con cụ thể).`,
    `  3. "Nên đi {{topic}} vào mùa nào" (BẮT BUỘC chứa từ "mùa" hoặc "thời điểm" — câu hỏi`,
    `     search intent hàng đầu với điểm đến lớn, KHÔNG được bỏ qua).`,
    `  4. "Lịch trình gợi ý đi {{topic}}" (gợi ý 1-2 mẫu lịch trình dạng "2N1D"/"3N2D" — viết`,
    `     dạng văn xuôi có cấu trúc theo ngày/buổi (vd "Ngày 1 buổi sáng... buổi chiều...", có`,
    `     thể dùng danh sách <ul>/<ol> trong câu chữ), nhắc tên điểm tham quan con cụ thể cho`,
    `     từng buổi để hệ thống tự gắn link nội bộ — KHÔNG lặp lại nội dung đã nói ở khối`,
    `     "trai-nghiem" (khối đó là danh sách hoạt động rời rạc, khối này là cách SẮP XẾP`,
    `     chúng theo thời gian thành lịch trình cụ thể).`,
    `  5. "Di chuyển tới {{topic}}" (2 CHIỀU từ các thành phố lớn).`,
    `  6. "Ăn gì đặc trưng ở {{topic}}" (đặc sản tiêu biểu cả vùng — sẽ viết dạng DANH SÁCH).`,
    `  7. "Quà mang về từ {{topic}}" (sẽ viết dạng DANH SÁCH).`,
    `- KHÔNG đặt heading liệt kê giờ mở cửa/giá vé riêng (mỗi điểm tham quan con có trang`,
    `  riêng cho việc đó) — bài này ở tầm tổng quan cả vùng.`,
    `- plannedFaqQuestions: 3-6 câu đúng search intent tổng quan (nên đi mấy ngày, đi mùa nào,`,
    `  di chuyển thế nào, có gì đặc trưng...).`,
    `- KHÔNG tự chế số liệu ngoài dữ liệu được cung cấp.`,
  ].join("\n"),

  "guide-diem-den-flagship.section.vi": [
    `Viết nội dung cho MỘT section của bài giới thiệu TỔNG QUAN 1 điểm đến lớn (tỉnh/cụm).`,
    `Bài viết: {{title}}`,
    `Section cần viết (heading phải giữ nguyên): {{sectionHeading}}`,
    `Toàn bộ outline (giữ mạch bài, KHÔNG lặp nội dung section khác): {{outline}}`,
    `DỮ LIỆU ĐIỂM ĐẾN (nguồn sự thật): {{sourceContext}}`,
    `Giọng văn: {{toneProfile}}`,
    ``,
    `Yêu cầu:`,
    VIETNAMESE_RULE,
    `- blockKey: BẮT BUỘC gán đúng 1 trong 7 giá trị sau theo đúng ý nghĩa heading đang viết —`,
    `  "tong-quan" | "trai-nghiem" | "mua-nao" | "lich-trinh" | "di-chuyen" | "an-gi" |`,
    `  "qua-mang-ve".`,
    `- content: 120-250 từ, góc nhìn TỔNG QUAN cả vùng — không đi sâu chi tiết 1 điểm tham`,
    `  quan con cụ thể (các điểm con đã có trang riêng), tránh văn mẫu sáo rỗng.`,
    `- Nếu blockKey là "mua-nao": nêu rõ mùa nào đẹp nhất, mùa nào nên tránh (mưa/lễ hội đông),`,
    `  gợi ý thời điểm cụ thể trong năm nếu dữ liệu cho phép.`,
    `- Nếu blockKey là "lich-trinh": có thể dài hơn 250 từ nếu cần đủ 1-2 mẫu lịch trình theo`,
    `  ngày/buổi; dùng đúng TÊN CHUẨN các điểm tham quan con nhắc tới để hệ thống tự gắn link.`,
    `- NẾU blockKey là "trai-nghiem" | "an-gi" | "qua-mang-ve": BẮT BUỘC điền thêm "items" — mảng`,
    `  ít nhất 3 mục {ten, moTa}. Với "trai-nghiem": "ten" là 1 HOẠT ĐỘNG cụ thể tiêu biểu cả`,
    `  vùng (KHÔNG phải tên 1 điểm tham quan con), "moTa" nêu cách trải nghiệm/vì sao đáng làm.`,
    `  Với "an-gi"/"qua-mang-ve": "ten" là món/đặc sản tiêu biểu CẢ VÙNG (không phải của 1`,
    `  quán/điểm con cụ thể), "moTa" là mô tả ngắn 1-2 câu. "content" khi đó chỉ cần 1 câu dẫn`,
    `  ngắn, không lặp lại "items" và không lặp lại ý đã nói ở khối "tong-quan".`,
    `- Nếu bài nhắc tới điểm tham quan con trong danh sách điểm liên quan (trong dữ liệu),`,
    `  dùng đúng TÊN CHUẨN của điểm đó để hệ thống tự gắn link.`,
    `- Số liệu (khoảng cách, thời gian di chuyển) CHỈ lấy từ dữ liệu cung cấp; thiếu thì`,
    `  viết định tính, không bịa con số.`,
  ].join("\n"),

  "guide-diem-den-flagship.frame.vi": [
    `Hoàn thiện KHUNG bài giới thiệu TỔNG QUAN 1 điểm đến lớn (mọi phần TRỪ các section chính).`,
    `Điểm đến: {{topic}}`,
    `Từ khóa chính: {{keywords}}`,
    `Outline: {{outline}}`,
    `Tóm tắt các section đã viết: {{sectionsSummary}}`,
    `DỮ LIỆU ĐIỂM ĐẾN (nguồn sự thật): {{sourceContext}}`,
    `Giọng văn: {{toneProfile}}`,
    ``,
    `Yêu cầu:`,
    VIETNAMESE_RULE,
    `- title: giữ đúng title trong outline.`,
    `- intro: 80-150 từ mở bài tự nhiên, chứa tên điểm đến, nêu cả địa chỉ MỚI và địa chỉ CŨ`,
    `  (trước sáp nhập) nếu dữ liệu có đủ cả hai.`,
    `- quickFacts (điểm đến lớn KHÔNG có 1 giờ/giá duy nhất — ghi đúng theo schema nhưng`,
    `  ở tầm tổng quan, KHÔNG bịa số của riêng 1 điểm con):`,
    `  openingTime, ticketPrice: ghi "Tuỳ điểm tham quan cụ thể — xem trang từng điểm".`,
    `  transport: cách di chuyển 2 CHIỀU tới vùng này (từ các thành phố lớn, phương tiện,`,
    `  thời gian ước tính). food: 2-3 món/đặc sản TIÊU BIỂU của cả vùng (không phải của 1`,
    `  quán cụ thể). hotel: nên ở khu vực nào trong vùng. tip: 2-4 mẹo thực tế khi đi cả vùng.`,
    `- faq: trả lời các câu hỏi trong outline, mỗi câu 2-4 câu văn.`,
    `- updateNotice: ghi ĐÚNG NGUYÊN VĂN "Thông tin trong bài cập nhật tháng {{currentDate}},`,
    `  giá vé và giờ mở cửa có thể thay đổi." — dùng đúng tháng/năm {{currentDate}} được cung cấp.`,
    `- metadata: name = tên chuẩn có dấu; slugSuggestion = slug không dấu;`,
    `  metaTitle <= 140 ký tự; metaDescription 100-290 ký tự chứa từ khóa;`,
    `  description = mô tả 1-2 câu (50-900 ký tự); searchKeyword = các từ người dùng hay gõ, cách nhau dấu phẩy.`,
    `- KHÔNG claim tuyệt đối ("đẹp nhất Việt Nam", "duy nhất", "rẻ nhất") khi không có nguồn.`,
  ].join("\n"),

  // ===== CẨM NANG dichoithoi.com (dichoithoi-article-spec §1-§4, Phase 22 07/2026) =====
  "cam-nang.outline.vi": [
    `Tạo OUTLINE cho bài viết CẨM NANG TỔNG HỢP du lịch tiếng Việt (khác bài giới`,
    `thiệu 1 điểm đến — bài này gom nhiều điểm đến/khách sạn/tour theo 1 chủ đề,`,
    `vd "Các con thác đẹp tại Đà Lạt", "Khách sạn giá rẻ gần biển Nha Trang").`,
    `Chủ đề: {{topic}}`,
    `Từ khóa chính: {{keywords}}`,
    `Giọng văn: {{toneProfile}}`,
    `Tư liệu tham khảo (nếu có — ưu tiên dùng để bài không chung chung): {{sourceContext}}`,
    ``,
    `Yêu cầu:`,
    VIETNAMESE_RULE,
    `- title: 50-70 ký tự, chứa từ khóa chính, đúng dạng người dùng hay gõ tìm kiếm.`,
    `- sectionHeadings: 3-8 mục H2, mỗi mục là 1 nhóm nội dung thật (vd theo khu`,
    `  vực/loại hình/tiêu chí) — KHÔNG tạo heading rỗng chỉ để nhét khối động,`,
    `  mỗi heading phải có lý do nội dung riêng.`,
    `- KHÔNG tự chế tên địa điểm/khách sạn/tour cụ thể không có trong tư liệu —`,
    `  outline chỉ định hình CẤU TRÚC bài, dữ liệu thật được chèn ở bước viết section.`,
  ].join("\n"),

  "cam-nang.section.vi": [
    `Viết nội dung cho MỘT section của bài cẩm nang tổng hợp du lịch tiếng Việt.`,
    `Bài viết: {{title}}`,
    `Section cần viết (heading phải giữ nguyên): {{sectionHeading}}`,
    `Toàn bộ outline (giữ mạch bài, KHÔNG lặp nội dung section khác): {{outline}}`,
    `Tư liệu tham khảo: {{sourceContext}}`,
    `Giọng văn: {{toneProfile}}`,
    ``,
    `Yêu cầu:`,
    VIETNAMESE_RULE,
    `- content: 100-200 từ văn xuôi tự nhiên GIỚI THIỆU nhóm nội dung của section này`,
    `  (không liệt kê khô khan) — đây là phần dẫn dắt, KHÔNG phải danh sách thật.`,
    `- Nếu section này hợp với 1 khối danh sách động (điểm đến/khách sạn/tour/sản`,
    `  phẩm/món ăn liên quan chủ đề), thêm ĐÚNG 1 dòng RIÊNG BIỆT ngay sau đoạn văn,`,
    `  đúng cú pháp: [[block:KIND tham_so=gia_tri]] — KIND là 1 trong:`,
    `  destinations (tham số type/province, vd [[block:destinations province=lam-dong limit=6]]),`,
    `  hotels (tham số province), tours (tham số destination hoặc province),`,
    `  destination (tham số slug — 1 điểm cụ thể), products (tham số tag bắt buộc),`,
    `  food-spots (tham số tag bắt buộc, thường là slug điểm đến).`,
    `  KHÔNG BẮT BUỘC mọi section phải có khối — CHỈ chèn khi thật sự hợp ngữ cảnh`,
    `  (vd section liệt kê "khách sạn gần..." thì hợp khối hotels, section kể`,
    `  chuyện/cảm nhận thuần văn xuôi thì KHÔNG cần khối nào).`,
    `- KHÔNG tự chế slug/tỉnh không chắc chắn tồn tại — nếu không chắc, bỏ qua`,
    `  khối động cho section đó, chỉ viết văn xuôi.`,
    `- Token khối động phải nằm 1 mình trên 1 dòng, không lẫn vào câu văn.`,
  ].join("\n"),

  "cam-nang.frame.vi": [
    `Hoàn thiện KHUNG bài cẩm nang tổng hợp (mọi phần TRỪ các section chính đã viết xong).`,
    `Chủ đề: {{topic}}`,
    `Từ khóa chính: {{keywords}}`,
    `Outline: {{outline}}`,
    `Tóm tắt các section đã viết: {{sectionsSummary}}`,
    `Tư liệu tham khảo: {{sourceContext}}`,
    `Giọng văn: {{toneProfile}}`,
    ``,
    `Yêu cầu:`,
    VIETNAMESE_RULE,
    `- title: giữ đúng title trong outline.`,
    `- intro: 80-150 từ mở bài tự nhiên, nêu rõ bài này tổng hợp gì, dành cho ai.`,
    `- metadata.metaTitle <= 60 ký tự; metadata.metaDescription 50-250 ký tự chứa`,
    `  từ khóa chính; metadata.slugSuggestion = slug không dấu; metadata.searchKeyword`,
    `  = các từ người dùng hay gõ, cách nhau dấu phẩy.`,
    `- KHÔNG claim tuyệt đối ("tốt nhất", "duy nhất") khi không có nguồn xác nhận.`,
  ].join("\n"),

  // ===== KHUYENMAI laruki/dochoi3s (km-*) — 1 content, tag inline (laruki-dochoi3s-content-spec §4) =====
  // Default CHUNG; per-site/per-postType soan qua /prompts (key <site>.km-<postType>.<step>.vi).
  "km-bai-viet.outline.vi": [
    `Tạo OUTLINE bài viết affiliate/giới thiệu sản phẩm cho website {{siteCode}}, chuẩn SEO,`,
    `giọng tự nhiên như người viết thật.`,
    `Chủ đề: {{topic}}`,
    `Từ khóa chính: {{keywords}}`,
    `Giọng văn: {{toneProfile}}`,
    `NGỮ CẢNH (ghi chú người dùng, nguồn tham khảo có thể tiếng Anh, gợi ý tag, nội dung cũ nếu viết lại):`,
    `{{sourceContext}}`,
    ``,
    `Yêu cầu:`,
    VIETNAMESE_RULE,
    `- title: 50-70 ký tự, chứa từ khóa chính tự nhiên.`,
    `- sectionHeadings: 3-7 mục H2 hợp chủ đề và đúng niche của site`,
    `  (laruki: thời trang/làm đẹp — bối cảnh dùng, mẹo phối; dochoi3s: đồ chơi trẻ em —`,
    `  nhấn ĐỘ TUỔI phù hợp, AN TOÀN/vật liệu, kỹ năng phát triển).`,
    `- KHÔNG bịa số liệu sản phẩm/giá: danh sách sản phẩm sẽ do TAG [..] sinh ra khi publish.`,
    `- Bố cục có chỗ tự nhiên cho các khối tag (mục gợi ý sản phẩm, link mua, hỏi-đáp) — AI sẽ đặt tag ở bước viết.`,
  ].join("\n"),

  "km-bai-viet.section.vi": [
    `Viết nội dung MỘT section của bài viết cho website {{siteCode}}.`,
    `Bài viết: {{title}}`,
    `Section cần viết (giữ nguyên heading): {{sectionHeading}}`,
    `Toàn bộ outline (giữ mạch, KHÔNG lặp section khác): {{outline}}`,
    `NGỮ CẢNH (gợi ý tag + nội dung cũ nếu viết lại): {{sourceContext}}`,
    `Giọng văn: {{toneProfile}}`,
    ``,
    `Yêu cầu:`,
    VIETNAMESE_RULE,
    `- content: 120-300 từ, văn xuôi tự nhiên, hợp niche; KHÔNG khoa trương.`,
    `- TAG CMS — CHỦ ĐỘNG ĐỀ XUẤT: ở những chỗ THỰC SỰ hợp lý hãy tự đặt tag để CMS chèn dữ liệu thật`,
    `  (danh sách sản phẩm sau đoạn dẫn, link mua trong câu CTA, hỏi-đáp cuối bài, năm trong mốc thời gian).`,
    `  Đặt VỪA ĐỦ, KHÔNG nhồi tag. Mỗi tag kèm 1 câu dẫn ngắn để người đọc hiểu khối sắp hiện.`,
    `- Cú pháp CHÍNH XÁC: [Type_Param:v1,v2;Param2:v;FlagParam]`,
    `  (params ngăn bằng ';', nhiều value bằng ','; flag không cần ':value'). Sai 1 ký tự = mất block.`,
    `  Loại hợp lệ + param chính:`,
    `    • ProductList: SupplierCode | ProductTag | NumberProduct | Order(None/Price/Discount) | ShowTop | HeaderTitle`,
    `    • SaleList: SupplierCode (bắt buộc) | NumberProduct      • SellerList: SupplierCode (bắt buộc) | SellerCode`,
    `    • Product: ProductTag (bắt buộc)   • Link: Url|Text|ProductTag|Format   • QA: Code   • DateTime: Format(vd yyyy)`,
    `  VD: [ProductList_ProductTag:lap-rap-co-khi;NumberProduct:5;ShowTop;HeaderTitle:5 SẢN PHẨM GỢI Ý]`,
    `- MÃ trong tag (SupplierCode/ProductTag/Url/Code): điền mã NGƯỜI DÙNG cấp trong "gợi ý tag" hoặc giữ từ nội dung cũ.`,
    `  Nếu vị trí đó NÊN có tag nhưng CHƯA có mã, VẪN đặt tag với placeholder "CAN_DIEN_MA" để người dùng điền sau`,
    `  (vd [ProductList_ProductTag:CAN_DIEN_MA;NumberProduct:5]). TUYỆT ĐỐI KHÔNG tự bịa mã thật.`,
    `- Tag để TRÊN DÒNG RIÊNG, KHÔNG bọc trong câu/đoạn.`,
    `- GIỮ NGUYÊN từng tag [..] (kể cả thứ tự param) đã có trong "nội dung hiện tại" khi viết lại — KHÔNG xóa/sửa.`,
    `- KHÔNG bịa thông số/giá sản phẩm: số liệu do tag thay thế khi publish.`,
  ].join("\n"),

  "km-bai-viet.frame.vi": [
    `Hoàn thiện KHUNG bài viết cho website {{siteCode}} (mọi phần TRỪ các section đã viết).`,
    `Chủ đề: {{topic}}`,
    `Từ khóa chính: {{keywords}}`,
    `Outline: {{outline}}`,
    `Tóm tắt các section đã viết: {{sectionsSummary}}`,
    ``,
    `Yêu cầu:`,
    VIETNAMESE_RULE,
    `- title: giữ đúng title trong outline.`,
    `- excerpt: 1-2 câu (50-300 ký tự) tóm tắt bài, chứa từ khóa chính — dùng cho mô tả ngắn.`,
  ].join("\n"),
};
